# Generated by Django 5.2.1 on 2025-05-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Togri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': "Togri so'zlar",
            },
        ),
        migrations.CreateModel(
            name='Notogri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=50)),
                ('togri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.togri')),
            ],
            options={
                'verbose_name_plural': "Notogri so'zlar",
            },
        ),
    ]
